import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * supplier_products.store_hidden — off the public shelf, everything else unchanged.
 *
 * Every existing way to remove a product from the store cost something else: `status`
 * takes it out of the campaign rotation too, `no_auto_post` stops the autopilot but
 * leaves it on the shelf, and deleting loses the FLYLINK link that was generated by hand
 * on the seller's site and cannot be regenerated from anything we hold.
 *
 * So the owner had no way to say the one thing he actually meant — "not this one, in the
 * shop" — without giving up something he did not intend to.
 */
export class AddStoreHidden1794000000000 implements MigrationInterface {
  name = 'AddStoreHidden1794000000000';

  public async up(q: QueryRunner): Promise<void> {
    await q.query(`ALTER TABLE supplier_products
                   ADD COLUMN IF NOT EXISTS store_hidden boolean NOT NULL DEFAULT false`);
  }

  public async down(q: QueryRunner): Promise<void> {
    await q.query(`ALTER TABLE supplier_products DROP COLUMN IF EXISTS store_hidden`);
  }
}
